{{- if .Values.deployClusterServiceBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: broker-skeleton
spec:
  url: http://broker-skeleton-broker-skeleton.broker-skeleton.svc.cluster.local
{{- end }}
